config/routes.rb
AdopteApp::Application.routes.draw do

  scope "(:locale)" do
    resources :users do
      member do
        get :following, :followers
        get :admin_edit
        get :edit_profile
        post :update_profile
      end
    end
    

    resources :password_resets
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]

    resources :products
    resources :line_items
    resources :carts
    resources :orders
    resources :categories

    resources :line_items do
      put 'decrement', on: :member
    end

    resources :products do
      get :who_bought, on: :member
    end

    resources :orders do
      collection do
        post '/by_date', :to => :orders_by_date
      end
    end

    get '/test1', :to => 'test_js#test1'
    get '/test2', :to => 'test_js#test2'

    get "/users/new"
    get '/contact', :to => 'pages#contact'
    get '/about', :to =>  'pages#about'
    get '/help', :to => 'pages#help'
    get '/site', :to =>  'pages#index'
    get '/home', :to => 'pages#home'
    get '/search', :to => 'pages#search'
    get '/autocomplete', :to => 'users#autocomplete'
    get '/signup', :to => 'users#new'

    get '/data_file', :to => 'data_file#index'
    post '/uploadFile', :to => 'data_file#uploadFile'
    get '/file', :to => 'data_file#show'

    get "password_resets/new"
    get "relationships/create"
    get "relationships/destroy"
    
    get '/search', :to => 'searches#show'

    controller :sessions do
      get 'signin' => :new
      post 'signin' => :create
      delete 'signout' => :destroy
    end

    get '/store', :to => 'store#index', as: 'store'

    get '/admin', :to => 'admin#index'

    root :to => 'store#index'

  end

get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/views/shared/_error_messages.html.erb
<%
 # object: f.object creates a variable called object in the error_messages partial.
 # We can use this object to construct a customized error message
%>
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-error">
		<% if object.errors.count > 1 %>
		<%= t :sign_up_form_errors, :count => object.errors.count %>
		<% else %>
		<%= t :sign_up_form_error, :count => object.errors.count %>
		<% end%>
		<!-- , :count => @user.errors.count -->
	</div>
	<p>
		<% if object.errors.count > 1 %>
		<%= t :sign_up_form_more_errors_message %>
		<% else %>
		<%= t :sign_up_form_one_error_message %>
		<% end%>
		<%
		# pluralize(@user.errors.count, 'this') 
		%>
	</p>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
		<li>
			* <%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<span class="user"> <%= link_to feed_item.user.nom, feed_item.user %> </span>
	<span class="content"><%= feed_item.content %></span>
	<span class="timestamp"> <%= "#{t :posted} #{time_ago_in_words(feed_item.created_at)} #{t :ago}..."%></span>
	<% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "#{t :delete_confirmation}" },
                                     title: feed_item.content,
                                     remote: true,
                                     :class => 'delete_feed_item' %>
  <% end %>
</li>

app/views/shared/_feed_product.html.erb
<% if @feed_product.any? %>
  <ol class="microposts">
    <%= render partial: 'shared/product_item', collection: @feed_product %>
  </ol>
  <%= will_paginate @feed_product %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
<div class="field">
	<%= f.text_area :content, placeholder: "#{t :compose_post}" %>
</div>
<%= f.submit "#{t :post}", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_product_item.html.erb
<li id="<%= product_item.id %>">
	<%= link_to image_tag(product_item.image_url) ,user_path( product_item.user) %>
	<span class="user"> <%= link_to product_item.user.nom, user_path( product_item.user) %> </span>
	<span class="content"><%= product_item.title %></span>
	<span class="content"><%= truncate(product_item.description, length: 100) %></span>
	<span class="timestamp"> Price :<span class="label label-info"><%= product_item.price %> </span> | Ctaegory <span class="label label-info"><%= product_item.category.name %></span> | <%= link_to "lien vers ..", product_path(product_item)%></span>
	<span class="timestamp"> <%= "#{t :posted} #{time_ago_in_words(product_item.created_at)} #{t :ago}..."%></span>

	<% if current_user?(product_item.user_id) %>
	<%= link_to "delete", feed_item, method: :delete,
	data: { confirm: "#{t :delete_confirmation}" },
	title: feed_item.content,
	remote: true,
	:class => 'delete_feed_item' %>
	<% end %>
</li>

app/views/shared/_search_product.html.erb
<h4> <%= t :search_result %> (Products)</h4>

<% unless @products.nil? %>
<table class="table table-striped table-bordered table-hover">

	<thead>
		<th> Image </th>
		<th> Description </th>
		<th> Prix </th>
		<th class="hidden-phone"> Catégorie </th>
		<th> Actuellement </th>

	</thead>
	<%if signed_in? %>
	<tfoot>

		<td colspan="4">
		<p>

			<div  class="offset3 hidden-desktop">
				<%= will_paginate @products, :page_links => false  %>
			</div>
		</p>
		<p>

			<div class="offset2 hidden-phone" >
				<%= will_paginate @products %>
			</div>
		</p></td>

	</tfoot>
	<%end%>
	<tbody>
		<%= render @products %>
	</tbody>

</table>

<%end%>

app/views/shared/_search_user.html.erb
<div class="row">
	<aside class="span3">
	</aside>
	<div class="span5">
		
		<h4> <%= t :search_result %> (Users)</h4>
		<ul class="users">
			<%= render @users unless @users.nil? %>
		</ul>

	</div>
</div>

app/views/shared/_stats.html.erb
<%
# si @user est différent de nil nous sommes dans la page de profile sinon 
# on lui affecte la valeur de l'utlisateur courant car ça signifie que nous somme dans la page de home
%>

<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>"> 
		<strong id="following" class="stat"> 
			<%= @user.followed_users.count %> 
		</strong> following 
	</a>
	<a href="<%= followers_user_path(@user) %>"> 

		<strong id="followers" class="stat"> 
			<%= @user.followers.count %> 
		</strong> followers 
	</a>
</div>

app/views/shared/_user_info.html.erb
<div id="user_info">
<a href="<%= user_path(current_user) %>"> <%= gravatar_for current_user, size: 52 %> </a>
<h1> <%= current_user.nom %> </h1>
<span> <%= link_to "#{t :view_my_profile}", current_user %> </span>
<span> <%= pluralize(current_user.microposts.count, "micropost") %> </span>
</div>