config/routes.rb
AdopteApp::Application.routes.draw do

  scope "(:locale)" do
    resources :users do
      member do
        get :following, :followers
        get :admin_edit
        get :edit_profile
        post :update_profile
      end
    end
    

    resources :password_resets
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]

    resources :products
    resources :line_items
    resources :carts
    resources :orders
    resources :categories

    resources :line_items do
      put 'decrement', on: :member
    end

    resources :products do
      get :who_bought, on: :member
    end

    resources :orders do
      collection do
        post '/by_date', :to => :orders_by_date
      end
    end

    get '/test1', :to => 'test_js#test1'
    get '/test2', :to => 'test_js#test2'

    get "/users/new"
    get '/contact', :to => 'pages#contact'
    get '/about', :to =>  'pages#about'
    get '/help', :to => 'pages#help'
    get '/site', :to =>  'pages#index'
    get '/home', :to => 'pages#home'
    get '/search', :to => 'pages#search'
    get '/autocomplete', :to => 'users#autocomplete'
    get '/signup', :to => 'users#new'

    get '/data_file', :to => 'data_file#index'
    post '/uploadFile', :to => 'data_file#uploadFile'
    get '/file', :to => 'data_file#show'

    get "password_resets/new"
    get "relationships/create"
    get "relationships/destroy"
    
    get '/search', :to => 'searches#show'

    controller :sessions do
      get 'signin' => :new
      post 'signin' => :create
      delete 'signout' => :destroy
    end

    get '/store', :to => 'store#index', as: 'store'

    get '/admin', :to => 'admin#index'

    root :to => 'store#index'

  end

get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy
  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
    current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end

  def decrement_line_item_quantity(line_item_id)
    current_item = line_items.find(line_item_id)
    if current_item.quantity > 1
    current_item.quantity -= 1
    else
    current_item.destroy
    end
    current_item
  end

  #calcul le prix total de tous le cadie
  #to_a.sum sum the prices of each item in the collection
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end
end
# == Schema Information
#
# Table name: carts
#
#  id         :integer         not null, primary key
#  created_at :datetime
#  updated_at :datetime
#

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  # rescue_from ActiveRecord::RecordNotFound, :with => render_404
  
  skip_before_filter :authorize, only: [:create, :update, :destroy, :show]
  #
  #
  # def render_404
  # render :status => 404, :text => 'not found'
  # end
  # GET /carts
  # GET /carts.json
  def index
    @cart = current_cart
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url
      flash[:error] = t :invalid_cart
    else
      respond_to do |format|
        format.html # show.html.erb
         format.js 
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])
    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart }
         flash[:success] = t :success_create_cart 
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart }
         flash.now[:success] = t :success_update_cart 
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<div id="cart_affichage">
<% if cart.line_items.empty? %> <h2><%= t :cart_empty %></h2>
<%else%>
<h2>Votre Panier</h2>
<table class="table table-striped table-hover">
	<thead class="table-bordered">
		<th> Qt </th>
		<th> Libelé </th>
		<th class="hidden">Description</th>
		<th class="hidden">Image</th>
		<th> Prix </th>
		<th>Action</th>
	</thead>
	<%= render(cart.line_items) %>
	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
	</tr>
</table>
<%= button_to "#{t :checkout}", new_order_path, class: "btn btn-mini", method: :get %>
<%= button_to "#{t :empty}", cart, class: "btn btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>
<%end%>
</div>
 <%=t :cart%> <span id="cart_count" class="hidden badge badge-inverse"> (<%= cart.line_items.count %>)</span>

app/views/carts/_cart_count.html.erb
<%=t :cart%> <span id="cart_count" class="hidden badge badge-inverse"> (<%= cart.line_items.count %>)</span>

app/views/carts/_empty_cart.html.erb
<h1>Votre Caddie est Vide</h1>

app/views/carts/_form.html.erb
<%= form_for(@cart) do |f| %>
  <% if @cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% @cart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing cart</h1>

<%= render 'form' %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<h1>Listing carts</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New cart</h1>

<%= render 'form' %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<% unless cart.line_items.empty? %>
<% if notice %>
<p id="notice">
	<%= notice %>
</p>
<% end %>
 <h2>Your Cart</h2>
<table>
	<%= render(@cart.line_items) %>
	<tr class="total_line">
		<td colspan="2">Total</td>
		<td class="total_cell"><%= number_to_currency(@cart.total_price, unit: "€") %></td>
	</tr>
</table>
<%= button_to 'Empty cart', @cart, class: "btn btn-mini", method: :delete, data: { confirm: 'Are you sure?' } %>

<% end %>

app/views/carts/show.js.erb
$(document).ready(function() {
  
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);
 
$("#side #cart, #tab2").click(showcart());

$('#tab2, #cart').html("<%= j(render(@cart))%>");

//#side_cart

if ($('#cart tr, #tab2 tr').length == 1) {
	 // Hide the cart
	 $('#cart').hide('blind', 1000); 
	 $('#cart #remove_one_item').remove();
}

 
$("#side #cart, #tab2").click(showcart());

function showcart() {

 if ($('#tab2_cart > .active')) {
		// code to be executed if condition is true
		$("#tab2").children().removeClass("hidden");
		$("#tab2 table th").removeClass("hidden");
		$("#tab2 table").addClass("table-bordered");
		$("#page_cart").children().removeClass("hidden");
$("#tab2 table tr td ").removeClass("hidden");
$("#tab2 table").addClass("table-hover table");
$("#tab2 table tr.total_line").addClass("info");
$("#tab2").show();
$("#page_cart").show();

	} else {
		// code to be executed if condition is false
		$("#tab2").hide();
		$("#page_cart").hide();
		$("#page_cart").addClass("hidden");
		$("#tab2").children().addClass("hidden");
		$("#tab2").addClass("hidden");
		$("#tab2 table").removeClass("table-hover table");
		$("#tab2 table tr.total_line").removeClass("info");
	}


$("#cart").show();

}

$('#flash_message').hide();




});