config/routes.rb
AdopteApp::Application.routes.draw do

  scope "(:locale)" do
    resources :users do
      member do
        get :following, :followers
        get :admin_edit
        get :edit_profile
        post :update_profile
      end
    end
    

    resources :password_resets
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]

    resources :products
    resources :line_items
    resources :carts
    resources :orders
    resources :categories

    resources :line_items do
      put 'decrement', on: :member
    end

    resources :products do
      get :who_bought, on: :member
    end

    resources :orders do
      collection do
        post '/by_date', :to => :orders_by_date
      end
    end

    get '/test1', :to => 'test_js#test1'
    get '/test2', :to => 'test_js#test2'

    get "/users/new"
    get '/contact', :to => 'pages#contact'
    get '/about', :to =>  'pages#about'
    get '/help', :to => 'pages#help'
    get '/site', :to =>  'pages#index'
    get '/home', :to => 'pages#home'
    get '/search', :to => 'pages#search'
    get '/autocomplete', :to => 'users#autocomplete'
    get '/signup', :to => 'users#new'

    get '/data_file', :to => 'data_file#index'
    post '/uploadFile', :to => 'data_file#uploadFile'
    get '/file', :to => 'data_file#show'

    get "password_resets/new"
    get "relationships/create"
    get "relationships/destroy"
    
    get '/search', :to => 'searches#show'

    controller :sessions do
      get 'signin' => :new
      post 'signin' => :create
      delete 'signout' => :destroy
    end

    get '/store', :to => 'store#index', as: 'store'

    get '/admin', :to => 'admin#index'

    root :to => 'store#index'

  end

get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :line_items
  has_many :orders, through: :line_items
  validates_associated :category

  before_destroy :ensure_not_referenced_by_any_line_item

  attr_accessible :description, :image_url, :price, :title, :category_id, :user_id, :status
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  #
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, length: {minimum: 5}


 
 
  CATEGORIES = Category.find(:all).collect {|category| category.id}

  belongs_to :category
  validates :category_id, inclusion: CATEGORIES
  # def category
  # Category.find_by_id(category_id).name
  # end

  PRODUCT_STATUS = ["Disponible","Indisponible", "Déstockage", "Solde", "Promotion"]
  validates :status, inclusion: PRODUCT_STATUS, presence: {:is => true, :message => "vous devez indiquer le statut du produit"}
  
  belongs_to :user
  validates :user_id, presence: true
  def user
    User.find_by_id(user_id)
  end
    
  def status_class
    
    case status # a_variable is the variable we want to compare
    when "Disponible"  #compare to 1
    @status =  "success"
    when "Indisponible" #compare to 2
    @status =  "warning" 
    when "Déstockage" #compare to 2
    @status =  "important" 
    when "Solde" #compare to 2
    @status =  "info" 
    when "Promotion" #compare to 2
    @status =  "info" 
    else
    @status =  "inverse" 
    end

  end
  
  
  
  #********************* Search ********************
  def self.search(search)
    if search
      find(:all, :conditions => [ "lower(title) LIKE ? OR lower(status) LIKE ? OR lower(status) LIKE ?", "%#{search}%".downcase, "%#{search}%".downcase, "%#{search}%".downcase ], :order => 'title' )
    else
      find(:all)
    end
  end

  

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
    return true
    else
      errors.add(:base, 'Line Items present')
    return false
    end
  end
end# == Schema Information

#
# Table name: products
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime
#  updated_at  :datetime
#

# == Schema Information
#
# Table name: products
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer
#  user_id     :integer
#  status      :string(255)
#

# == Schema Information
#
# Table name: products
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer
#  user_id     :integer
#  status      :string(255)
#

# == Schema Information
#
# Table name: products
#
#  id          :integer         not null, primary key
#  title       :string(255)
#  description :text
#  image_url   :string(255)
#  price       :decimal(8, 2)
#  created_at  :datetime
#  updated_at  :datetime
#  category_id :integer
#  user_id     :integer
#  status      :string(255)
#

app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  skip_before_filter :authorize, only:[:show]
  before_filter :true_owner,   only: [:update,:destroy, :who_bought, :edit]
  # GET /products
  # GET /products.json
  def index
    if current_user.admin?
      @products = Product.paginate(page: params[:page],:per_page=> 10)
    else
      @products = Product.where(:user_id => current_user.id).paginate(page: params[:page],:per_page=> 10)
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
      format.js
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    @remote_product = @product
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
      # format.js { render js: "show_product"}
      format.js
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create

    @product = current_user.products.build(params[:product])
    #@product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product}
        flash[:success] = 'Le produit à bien été ahouté.'
        format.json { render json: @product, status: :created,
          location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product}
        flash[:success] = t :product_update_success
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.atom
      format.json { render json: @product}
      format.xml { render xml: @product}
    end
  end

  private

  def true_owner
    @product = current_user.products.find_by_id(params[:id])
    #@micropost.any? ? @old_micropost = @micropost : @old_micropost = []
    if @product.nil? && !current_user.admin?
      redirect_to :home
      flash[:errors] = 'Action non autorisée!'
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
  
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>

<p>
	<%= render 'shared/error_messages', object: f.object %>
</p>

<div class="field">
	<%= f.label :title %>
	<br>
	<%= f.text_field :title %>
</div>
<div class="field">
	<%= f.label :description %>
	<br>
	<%= f.text_area :description, rows: 6 %>
</div>
<div class="field">
	<%= f.label :image_url %>
	<br>
	<%= f.text_field :image_url %>
	<%= link_to "charger une image", data_file_url %>
</div>

<div class="form_style">
	<p>
		<%= form_tag('/uploadFile', :multipart => true) %>
		<label for="upload_file">Charger un fichier</label>
		<%= file_field :upload, 'datafile' %>
		<%= submit_tag "Charger", :class=>"btn btn-small", :name => "upload" %>
	</p>

</div>

<div class="field">
	<%= f.label :price %>
	<br>
	<%= f.text_field :price %>
</div>
<div class="field">
	<%= f.label :category_id, "Catégorie" %>
	<br>
	<%= collection_select(:product, :category_id, Category.all,:id, :name,  prompt: 'Choisir une catégorie') %>

</div>

<div class="field">
	<%= f.label :status, "Statut" %>
	<br>
	<%= f.select :status, Product::PRODUCT_STATUS,
	prompt: 'Indiquer le statut du produit' %>
</div>

<button type="submit" class="btn btn-small">
	valider
	</button>
<% end %>

app/views/products/_index.html.erb
<h1>Listing des Produits</h1>

<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>Titre</th>
			<th>Description</th>
			<th>Image url</th>
			<th>Price</th>
			<th>Catégorie</th>
			<th>Actions</th>
		</tr>
	</thead>

	<tbody>
		<%= render @products unless @products.nil? %>
	</tbody>

</table>
<div class="span8 offset2">
	<%= will_paginate @products unless @products.nil? %>
	<%= link_to 'Nouveau Product', new_product_path %>
</div>
<br>

app/views/products/_product.html.erb
<tr>
	<td rowspan="2"> <%= image_tag(product.image_url)%> </td>
</tr>
<tr>

	<td><h4><%= product.title %></h4>
	<p>
		<%=product.description%>
	</p></td>

	<td>
	<div class="price_line entry">

		<span class="price"><%= number_to_currency(product.price, :unit => '€') %></span>
		<% if product.status == "Indisponible" %>

		<a href="#" data-toggle="tooltip" title="Produit indisponible"><%= button_to "#{t :add_item}", '#indisponible', remote: true, :class => "btn btn-mini btn_add  disabled" %></a>

		<% else %>
		<%= button_to "#{t :add_item}", line_items_path(product_id: product), remote: true, :class => "btn btn-mini btn_add" %>
		<% end %>
	</div></td>
	<td class="hidden-phone"><span class="label label-inverse"><%= product.category.name%></span></td>
	<td><span class="label pull-right label-<%= product.status_class %>"><%= product.status%></span> <% if product.status == "Solde" %>
	<%= image_tag("soldes.jpg") %> </td>
	<% end %>

</tr>

app/views/products/_show.html.erb
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
		&times;
	</button>
	<h3>Détails du produit</h3>
</div>

<% unless @product.nil? %>
<table class="table table-striped table-bordered table-hover">

	<thead>
		<th> Image </th>
		<th> Description </th>
		<th> Prix </th>
		<th> Catégorie </th>
		<th> Actuellement </th>

	</thead>
	<%if signed_in? %>
	<tfoot>

		<td colspan="4">
		<div class="offset3">
			
			<%= link_to "#{t :edit}", edit_product_path(@product) %> |
			<%= link_to  "#{t :back}" , products_path %>
			
		</div></td>

	</tfoot>
	<%end%>
<tbody>
	
	<tr>
		<td rowspan="2"> <%= image_tag(@product.image_url)%> </td>
	</tr>
	<tr>

		<td><h4><%= @product.title %></h4>
		<p>
			<%= @product.description %>
		</p></td>

		<td>
		<div class="price_line entry">

			<span class="price"><%= number_to_currency(@product.price, :unit => '€') %></span>
			<% if @product.status == "Indisponible" %>

			<a href="#" data-toggle="tooltip" title="Produit indisponible"><%= button_to "#{t :add_item}", '#indisponible', remote: true, :class => "btn btn-mini btn_add  disabled" %></a>

			<% else %>
			<%= button_to "#{t :add_item}", line_items_path(product_id: @product), remote: true, :class => "btn btn-mini btn_add" %>
			<% end %>
		</div></td>
		<td><span class="label label-inverse"><%= @product.category.name%></span></td>
		<td><span class="label pull-right label-<%= @product.status_class %>"><%= @product.status%></span> <% if @product.status == "Solde" %>
		<%= image_tag("soldes.jpg") %> </td>
		<% end %>

	</tr>
	</tbody>

</table>

<%end%>

<footer>
	<div class="modal-footer">
		<button class="btn" data-dismiss="modal" aria-hidden="true">
			Fermer
		</button>
	</div>
</footer>

app/views/products/edit.html.erb
<div class="depot_form form_style">
	<div class="row">
		<div class="span9 offset2">
			<h4>Formulaire de modification | Produit!</h4>
			<fieldset>
				<legend></legend>
				<%= render 'form' %>
			</fieldset>

			<%= link_to "#{t :show}", @product %> |
			<%= link_to "#{t :back}", products_path %>
		</div>
	</div>
</div>

app/views/products/index.html.erb
<h1>Listing des Produits</h1>

<table class="table table-striped table-bordered table-hover">
	<thead>
		<tr>
			<th>Titre</th>
			<th>Description</th>
			<th>Image url</th>
			<th>Price</th>
			<th>Catégorie</th>
			<th>Actions</th>
		</tr>
	</thead>
	<tfoot>
		<td>Titre</td>
			<td>Description</td>
			<td>Image url</td>
			<td>Price</td>
			<td>Catégorie</td>
			<td>Actions</td>
	</tfoot>

	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= link_to product.title, product_path(product) %></td>
			<td><%= product.description %></td>
			<td><%= link_to product.image_url, file_path(:file => product.image_url) %></td>
			<td><%= product.price %></td>
			<td><%= link_to product.category.name, category_path(product.category) %></td>
			<td><%= link_to 'Voir', product %> | <%= link_to "Achat?", who_bought_product_path(product.id) %> | <%= link_to 'Modifier', edit_product_path(product) %> | <%= link_to 'Supprimer', product, method: :delete, data: { confirm: 'êtes-vous sûr?' } %></td>

		</tr>
		<% end %>
	</tbody>

</table>
<div class="span8 offset2">
	<%= will_paginate @products %>
	<%= link_to 'Nouveau Product', new_product_path %>
</div>
<br>

app/views/products/index.js.erb
$('#collapseTwoProduit').html("<%=j render @products %>");

app/views/products/new.html.erb
<div class="depot_form form_style admin_form">
	<div class="row">
		<div class="span6 offset3">
			<h4> Ajouter un Produit!</h4>
			<fieldset>
			<legend>
			</legend>
			<%= render 'form' %>
		</fieldset>
		<%= link_to "#{t :back}", products_path %>
		</div>
	</div>
</div>

app/views/products/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @product.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%=  image_tag(@product.image_url)  %>
</p>

<p>
  <strong>Price:</strong>
  <%= number_to_currency(@product.price) %>
</p>

<p>
  <strong>Catégorie</strong>
  <%= @product.category.name %>
</p>

<%if signed_in? %>
<%= link_to "#{t :edit}", edit_product_path(@product) %> |
<%= link_to  "#{t :back}" , products_path %>
<%end%>

app/views/products/show.js.erb
$('#show_product, #myModal').html("<%=j render 'products/show' %>");

app/views/products/who_bought.html.erb
<h2> <%= "Client ayant cheté le produit : <#{@product.title}>" %></h2>
<% latest_order = @product.orders.sort_by(&:updated_at).last %>

<% @product.orders.each do |order| %>

<h2><%= "Commande ref: #{order.id}"%></h2>

<h5> <%= "Envoyé à l'adreese:  #{order.address}"  %> </h5>

<table class="table table-striped table-bordered table-hover">
	<tr>
		<th> N°</th>
		<th> Produit </th>
		<th> Quantité </th>
		<th> Categorie </th>
		<th> Prix Unit. </th>
		
	</tr>
	<% i=0%>
	<% order.line_items.each do |item| %>

	<tr>
		<td><%= i+=1 %></td>
		<td> <%= item.product.title %> </td>
		<td> <%= item.quantity %> </td>
		<td> <%= item.product.category.name %> </td>
		<td> <%= number_to_currency(item.product.price, :unit => '€') %> </td>
	</tr>
	<%end%>
	<tr>
		<th></th>
		<th colspan="3" class="text-center"> Total </th>

		<th><%= number_to_currency(order.line_items.map(&:total_price).sum, unit: '€') %></th>
	</tr>

</table>
<table>
	<tr>
		<td> <%= "Moyen de Payement: #{order.pay_type}" %> </td><td>Par :</td> 
	</tr>
	<tr>
<td>Nom: <%= order.name %></td> <td>Prénom: <%= order.last_name %></td> <td>Email: <%= order.email %></td>
	</tr>
	
</table>
<hr />
<%end%>

app/views/products/who_bought.json.erb
atom_feed do |feed|
	feed.title "Who bought #{@product.title}"
	latest_order = @product.orders.sort_by(&:updated_at).last
	
	feed.updated( latest_order && latest_order.updated_at ) 
	@product.orders.each do |order|
		feed.entry(order) do |entry| 
			entry.title "Order #{order.id}"
			
			entry.summary type: 'xhtml' do |xhtml| 
				xhtml.p "Shipped to #{order.address}" 
				
				xhtml.table do 
					xhtml.tr do
						xhtml.th 'Product' 
						xhtml.th 'Quantity' 
						xhtml.th 'Total Price'
					end
					order.line_items.each do |item| 
						xhtml.tr do
							xhtml.td item.product.title
							xhtml.td item.quantity
							xhtml.td number_to_currency item.total_price
						end 
					end
					xhtml.tr do
						xhtml.th 'total', colspan: 2 
						xhtml.th number_to_currency \
						order.line_items.map(&:total_price).sum
					end 
				end
				xhtml.p "Paid by #{order.pay_type}"
			end
			entry.author do |author| 
				author.name order.name 
				author.email order.email
			end 
		end
	end 
end