config/routes.rb
AdopteApp::Application.routes.draw do

  scope "(:locale)" do
    resources :users do
      member do
        get :following, :followers
        get :admin_edit
        get :edit_profile
        post :update_profile
      end
    end
    

    resources :password_resets
    resources :sessions, :only => [:new, :create, :destroy]
    resources :microposts, only: [:index, :create, :destroy]
    resources :relationships, only: [:create, :destroy]

    resources :products
    resources :line_items
    resources :carts
    resources :orders
    resources :categories

    resources :line_items do
      put 'decrement', on: :member
    end

    resources :products do
      get :who_bought, on: :member
    end

    resources :orders do
      collection do
        post '/by_date', :to => :orders_by_date
      end
    end

    get '/test1', :to => 'test_js#test1'
    get '/test2', :to => 'test_js#test2'

    get "/users/new"
    get '/contact', :to => 'pages#contact'
    get '/about', :to =>  'pages#about'
    get '/help', :to => 'pages#help'
    get '/site', :to =>  'pages#index'
    get '/home', :to => 'pages#home'
    get '/search', :to => 'pages#search'
    get '/autocomplete', :to => 'users#autocomplete'
    get '/signup', :to => 'users#new'

    get '/data_file', :to => 'data_file#index'
    post '/uploadFile', :to => 'data_file#uploadFile'
    get '/file', :to => 'data_file#show'

    get "password_resets/new"
    get "relationships/create"
    get "relationships/destroy"
    
    get '/search', :to => 'searches#show'

    controller :sessions do
      get 'signin' => :new
      post 'signin' => :create
      delete 'signout' => :destroy
    end

    get '/store', :to => 'store#index', as: 'store'

    get '/admin', :to => 'admin#index'

    root :to => 'store#index'

  end

get ':not_found' => redirect('/'), :constraints => { :not_found => /.*/ }
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order
  attr_accessible :cart_id, :product_id
  
  #calcul le prix de pour chaque ligne de lineItem 
  def total_price
    product.price * quantity
  end
end
# == Schema Information
#
# Table name: line_items
#
#  id         :integer         not null, primary key
#  product_id :integer
#  cart_id    :integer
#  created_at :datetime
#  updated_at :datetime
#  quantity   :integer         default(1)
#  order_id   :integer
#

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :decrement]
  before_filter :admin_user,     only: [:edit, :update, :destroy]
  
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @line_items }
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    @cart = current_cart
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js   { @current_item = @line_item }
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/1/edit
  def edit
    @line_item = LineItem.find(params[:id])

  end

  # POST /line_items
  # POST /line_items.json
  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id)
    @line_item.product = product
  
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url }
        format.js { @current_item = @line_item }
        format.json { render json: @line_item,
          status: :created, location: @line_item }
      else
        format.html { render action: "new" }
        format.json { render json: @line_item.errors,
          status: :unprocessable_entity }
      end
    end
  end


  # PUT /line_items/1
  # PUT /line_items/1.json
  def update
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item = LineItem.find(params[:id])
    @line_item.destroy

    respond_to do |format|
      format.html { redirect_to line_items_url }
      format.json { head :no_content }
    end
  end
  
   
  #PUT /line_items/1
  #PUT /line_items/1.json
  def decrement
    @cart = current_cart
    @line_item = @cart.decrement_line_item_quantity(params[:id]) #passing in line_item.id
    # @line_item = @line_item.sort { |a,b| a.product.title <=> b.product.title }
    respond_to do |format|
      if @line_item.save
        format.html { redirected_to store_path }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.js   { @current_item = @line_item }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end
  
    def admin_user
    if !current_user.admin?
      redirect_to(root_path)
      flash[:errors] = 'Action non autorisée!'
    end
  end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
<p>
	<%= render 'shared/error_messages', object: f.object %>
</p>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
<tr id="current_item">
	<% else %>
<tr>
	<% end %>
	<td><%= line_item.quantity %>&times;</td>
	<td><%= line_item.product.title %></td>
	<td class="hidden"><%= truncate(line_item.product.description, length: 150) %></td>
	<td class="hidden"><%= image_tag(line_item.product.image_url) %></td>
	<td class="item_price"><%= number_to_currency(line_item.total_price, :unit =>"€ ") %></td>
	<td><%= button_to 'v', decrement_line_item_path(line_item),method: :put, :class => "btn btn-mini", remote: true, title: 'remove one item' %></td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s", line_item.quantity,
                             truncate(line_item.product.title, length: 50)) %>

app/views/line_items/create.js.erb
$('#notice').hide();
$('#flash_message').hide();
$('#flash_message, .alert').hide();


//#START_HIGHLIGHT
if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

//#END_HIGHLIGHT
$('#cart, #tab2, #side_cart').html("<%=j render @cart %>");

$("#side_cart #cart_count").removeClass("hidden");
$("#side_cart #cart_affichage").addClass("hidden");

$("#tab2 #cart_count, #cart #cart_count").addClass("hidden");

//on déverou le side bar sur l onglet Panier



//#side_cart
$('#current_item').css({'background-color':'#88ff88'}).
  animate({'background-color':'#114411'}, 1000);
  
  $("#side #cart, #tab2").click(showcart());

function showcart() {

 if ($('#tab2.active')) {
		// code to be executed if condition is true
		$("#tab2").children().removeClass("hidden");
		$("#tab2 table th").removeClass("hidden");
		$("#tab2 table").addClass("table-bordered");
		$("#page_cart").children().removeClass("hidden");
$("#tab2 table tr td ").removeClass("hidden");
$("#tab2 table").addClass("table-hover table");
$("#tab2 table tr.total_line").addClass("info");
$("#tab2").show();
$("#page_cart").show();

	} else {
		// code to be executed if condition is false
		$("#tab2").hide();
		$("#page_cart").hide();
		$("#page_cart").addClass("hidden");
		$("#tab2").children().addClass("hidden");
		$("#tab2").addClass("hidden");
		$("#tab2 table").removeClass("table-hover table");
		$("#tab2 table tr.total_line").removeClass("info");
	}


$("#cart").show();
}

app/views/line_items/decrement.js.erb
$(document).ready(function() {
  
$('#current_item').css({'background-color':'#88ff88'}).animate({'background-color':'#114411'}, 1000);
 
$("#side #cart, #tab2").click(showcart());

$('#cart, #tab2, #side_cart').html("<%=j render @cart %>");

$("#side_cart #cart_count").removeClass("hidden");
$("#side_cart #cart_affichage").addClass("hidden");

$("#tab2 #cart_count, #cart #cart_count").addClass("hidden");
//#side_cart

if ($('#cart tr, #tab2 tr').length == 1) {
	 // Hide the cart
	 $('#cart').hide('blind', 1000); 
	 $('#cart #remove_one_item').remove();
}

 
$("#side #cart, #tab2").click(showcart());

function showcart() {

 if ($('#tab2_cart > .active')) {
		// code to be executed if condition is true
		$("#tab2").children().removeClass("hidden");
			$("#tab2 table").addClass("table-bordered");
		
		$("#tab2 table th").removeClass("hidden");
		$("#page_cart").children().removeClass("hidden");
$("#tab2 table tr td ").removeClass("hidden");
$("#tab2 table").addClass("table-hover table");
$("#tab2 table tr.total_line").addClass("info");
$("#tab2").show();
$("#page_cart").show();

	} else {
		// code to be executed if condition is false
		$("#tab2").hide();
		$("#page_cart").hide();
		$("#page_cart").addClass("hidden");
		$("#tab2").children().addClass("hidden");
		$("#tab2").addClass("hidden");
		$("#tab2 table").removeClass("table-hover table");
		$("#tab2 table tr.total_line").removeClass("info");
	}


$("#cart").show();

}


$('#flash_message, .alert').hide();




});

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to "#{t :show}", @line_item %> |
<%= link_to "#{t :back}", line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product_id %></td>
        <td><%= line_item.cart_id %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to "#{t :back}", line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart_id %>
</p>

<% if signed_in? %>
<%= link_to "#{t :edit}", edit_line_item_path(@line_item) %> |
<%= link_to "#{t :back}", line_items_path %>
<%end%>